# Name of workflow
name: MyWebApp - Pull Request Workflow - Composite Action

# Workflow trigger event. We want the workflow to trigger on a pull
# request to main
on:
  pull_request:
    branches: 
      - main
  
jobs:

  # Build and test the PR
  build-test-branch:

    name: "Build Test Of PR using Composite Action"

    runs-on: ubuntu-latest

    steps:
    
    - name: Start Build Indicator
      run: |
        curl -X POST "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/effects/breathe" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'color=blue' -d 'period=4' -d 'cycles=450' -d 'from_color=pink'
      
    
    - name: Build / Test / Publish / Upload Code
      uses: mickeygoussetorg/github-actions-presentation-composite-action@release-demo
      with:
        solution: "${{ github.workspace }}/src/mywebapp.sln"
        config: "Release"
        cs-proj-file: "${{ github.workspace }}/src/mywebapp/mywebapp.csproj"
        published-files: mywebapp

    - name: Final build status indicator
      if: success()
      run: | 
        curl -X POST "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/effects/off" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'power_off=false'
        curl -X PUT "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/state" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'color=green'
        
    - name: Final build status indicator
      if: failure()
      run: | 
        curl -X POST "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/effects/off" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'power_off=false'
        curl -X PUT "https://api.lifx.com/v1/lights/${{ vars.LIFX_BULB_LOCATION }}/state" -H "Authorization: Bearer ${{ secrets.LIFX_TOKEN }}" -d 'color=red'
        
   
